### ISSUE TITLE
Add a feature flag to automate Windows coloring

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/yansi#25]
Basically, do the following automatically:

```rust
if !Paint::enable_windows_ascii() {
    Paint::disable()
}
```

The implementation should just check if painting is disabled via the already relaxed atomic bool and otherwise check a second atomic bool, also relaxes, to see if we've tried to enable Windows coloring already.

**Comment by epage** [comment]
imo `yansi` should do all or nothing.  I appreciate that its (mostly) not doing things behind my back.  The reason I was interested in `yansi` compared to `termcolor` (besides ergonomics) is `termcolor` half-implements the policy I need and implementing the rest felt like I was working against it rather than with it.

**Comment by SergioBenitez** [comment]
I think this is a rather special case. I don't want to care about the platform. Right now, I need to care about the platform. I cannot think of a single case where you would not want to write:

```rust
if !Paint::enable_windows_ascii() {
    Paint::disable()
}
```



> I appreciate that its (mostly) not doing things behind my back. The

What do you feel it does behind your back?

**Comment by epage** [comment]
> What do you feel it does behind your back?

- `--color always` would not be respected if `yansi` does this.
- I already have to maintain my own "disable" tracking that has its own logic, on top of what `Pain::disable` does (see #17, #18)

**Comment by SergioBenitez** [comment]
These are fantastic points, @epage! I'll think about this a bit.

**Comment by epage** [comment]
Tired of copy/pasting my herding of cats (all of the color use in my applications), I've done some [research on where Rust is at wrt to color](https://github.com/rust-cli/team/issues/15#issuecomment-891350115) and have created a [prototype](https://docs.rs/concolor-control) with a [PoC conversion of `termcolor`](https://github.com/BurntSushi/termcolor/pull/49) (since it has the most varied use cases).  I'd be interested in any feedback on the idea or design!

**Comment by SergioBenitez** [comment]
`v2` (in progress, see `v2` branch) automatically enabled support on Windows.
