### ISSUE TITLE
The method `clear` in trait `Paint` causes a conflict with `Vec::clear`

### ISSUE THREAD

**Issue by mohammadfawaz** [SergioBenitez/yansi#42]
Referring to https://docs.rs/yansi/1.0.0/yansi/trait.Paint.html#tymethod.clear

Here's a simple reproducer:
```rust
use yansi::Paint;

fn main() {
    let v = vec![1, 2];
    v.clear();
    println!("length of v: {}", v.len());
}
```
Output:
```console
length of v: 2
```
Took me a while to figure out why my vectors were not clearing. Maybe changing the name of the method would help here? I'm honestly surprised that `rustc` does not complain about this in the first place.

**Comment by SergioBenitez** [comment]
Fascinating. Rust is selecting the `Paint::clear()` method _before_ the `Vec::clear()` method because the former takes an `&self` as a receiver and the latter an `&mut self`, despite the latter being an inherent method.

This is indeed quite unfortunate. We cannot change the name without a major version bump. It would have been useful to know this before the v1 release. The only thing we can do without needing a v2 of the library is to deprecate the method in favor of a different one. And perhaps in due time, we can release a version without the method and yank 1.0.0, even if it is a semantically breaking change.

**Comment by SergioBenitez** [comment]
What shall we rename the method, however? My first inclination was `reset()`, but there's [`tokio::Internal::reset()`](https://docs.rs/tokio/latest/tokio/time/struct.Interval.html#method.reset), and we'd have the same problem there as a result.

**Comment by mohammadfawaz** [comment]
Note that, even if `v` was declared `mut`, the problem persists:
```rust
use yansi::Paint;

fn main() {
    let mut v = vec![1, 2];
    v.push(3);
    v.clear();
    println!("length of v: {}", v.len());
}
```
```console
length of v: 3
```
so it looks like `rustc` is always choosing the user-imported method and ignoring the standard library method.

In any case, I realize that changing the name is not ideal, but my main worry is that developers will have a hard time debugging seemingly innocent code. I ran into this as I was bumping from `yansi 0.5` to `yansi 1.0` and took me a while to figure out why my tests started failing. 

As for alternative names: `cleanse` and `unset` are reasonable. `clean` may also work?

In any case, great work on this library! It's super useful :)

**Comment by SergioBenitez** [comment]
> so it looks like rustc is always choosing the user-imported method and ignoring the standard library method.

As I mentioned, it's choosing the trait method because of the receiver being an immutable reference, not simply because it's a trait method. If `Vec::clear()` instead took an immutable reference, or if `Paint::clear()` took a mutable reference, it would instead prefer the inherent method.

I'll pick a different method name and follow the deprecate + breakage plan. Thank you for reporting this.
