### ISSUE TITLE
Allow conditions to accept closures

### ISSUE THREAD

**Issue by a1akris** [SergioBenitez/yansi#44]
First of all, thank you for this cool and easy to use library, this is my favourite terminal painter so far. Now on to the issue:

In my CLIs I usually have a flag that, when specified, outputs results in a machine readable format which can be easily parsed from scripts and this format strips all colors to avoid complications. I used a custom logic for this before but today I discovered the `whenever` method and refactored everything to use it where possible just to discover that the `Condition` accepts `fn() -> bool` and I cannot pass closures there. 

Fortunately, I can workaround this by setting an env variable and then reading it from `fn() -> bool` but it forces me to support this env variable everywhere now for consistency. Also, I can imagine other situations where you may want to decide to use colorful output or not based on the program logic itself and not on some external circumstances. 

My suggestion is to generalize `Condition` like `Condition<F: Fn() -> bool>(F)` or `Condition(Box<dyn Fn() -> bool>)` to handle more use cases. Formally it will be a breaking change but practically all old code that used `fns` should still work unless users pass `Condition` in their own functions which I highly doubt given the nature of the `fn() -> bool` signature.

**Comment by SergioBenitez** [comment]
The issue is two-fold: `Condition` needs to be something that can be stored in a `static`, and we want to avoid allocating to produce a `Style`. Unfortunately both suggestions would violate these properties. We would need specialization to overcome this. 

Nevertheless, it's likely that this isn't actually necessary for your use case. This is because you can use [Condition::cached()](https://docs.rs/yansi/latest/yansi/struct.Condition.html#method.cached) to store any boolean, even those computed at runtime, in a `Condition`.

**Comment by a1akris** [comment]
Thanks, I saw this method in the docs but I didn't notice that it accepts a simple bool, it appeared to me from the example that it still accepts `fn() -> bool`. The method also suffices to cover a dynamic conditions use case as long as you don't postpone a printing for too long so I'm closing the issue.
